# コメントが明るい色かつ通常の文章とコメントの色が異なるテーマをselectしたい
# theme = "base16_default"
# theme = "dark_plus"
# theme = "dracula"
# theme = "hex_steel"
# theme = "hex_toxic" # 選択箇所がまるで見えないのでよくない
theme = "monokai"
# theme = "zenburn"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
rulers = [80, 160]
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "

[editor.indent-guides]
render = true
character = "|"
