# コメントが明るい色かつ通常の文章とコメントの色が異なるテーマをselectしたい
theme = "doom_acario_dark"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.soft-wrap]
enable = true

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "

[editor.indent-guides]
render = true
# character = "▕"
character = "⢸"
