theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false
cursorline = true
true-color = true
rulers = [80, 160]
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "|"
