# made 20/11/08

#locale
#export LANG=ja_JP.UTF-8
export GLFW_IM_MODULE=fcitx5
export PATH="/opt/julia-1.7.3/bin/:$PATH"
export PATH="${HOME}/.local/bin/:$PATH"
export PATH="${HOME}/.roswell/bin/:$PATH"
export PATH="$PATH:${HOME}/.local/share/ponyup/bin/"
export PATH="${HOME}/Workspace/nvim-linux64/bin:$PATH"
export PATH="${HOME}/.local/kitty.app/bin:$PATH"
export MANPAGER=w3m
export WWW_HOME='file:///cgi-bin/toppage.cgi'
source $HOME/.cargo/env
[[ "$TERM" == "xterm-kitty" ]] && alias ssh="kitty +kitten ssh"
# [[ $SSH_CLIENT ]] && export $(echo $SSH_CLIENT| cut -d ' ' -f 1):0
#key bind
bindkey -v

# ビープ音を鳴らさないようにする
setopt no_beep           
# ディレクトリ名の入力のみで移動する 
setopt auto_cd           
# cd時にディレクトリスタックにpushdする
setopt auto_pushd        
# コマンドのスペルを訂正する
setopt correct           
# =以降も補完する(--prefix=/usrなど)
setopt magic_equal_subst 
# プロンプト定義内で変数置換やコマンド置換を扱う
setopt prompt_subst      
# バックグラウンドジョブの状態変化を即時報告する
setopt notify            
# =commandを`which command`と同じ処理にする
setopt equals            

### Complement ###
autoload -U compinit; compinit # 補完機能を有効にする
setopt auto_list               # 補完候補を一覧で表示する(d)
setopt auto_menu               # 補完キー連打で補完候補を順に表示する(d)
setopt list_packed             # 補完候補をできるだけ詰めて表示する
setopt list_types              # 補完候補にファイルの種類も表示する
bindkey "^[[Z" reverse-menu-complete  # Shift-Tabで補完候補を逆順する("\e[Z"でも動作する)
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # 補完時に大文字小文字を区別しない

### Glob ###
setopt extended_glob # グロブ機能を拡張する gitで使われる"^"と競合している
unsetopt caseglob    # ファイルグロブで大文字小文字を区別しない

### History ###
HISTFILE=~/.zsh_history   # ヒストリを保存するファイル
HISTSIZE=10000            # メモリに保存されるヒストリの件数
SAVEHIST=10000            # 保存されるヒストリの件数
setopt bang_hist          # !を使ったヒストリ展開を行う(d)
setopt extended_history   # ヒストリに実行時間も保存する
setopt hist_ignore_dups   # 直前と同じコマンドはヒストリに追加しない
setopt share_history      # 他のシェルのヒストリをリアルタイムで共有する
setopt hist_reduce_blanks # 余分なスペースを削除してヒストリに保存する
# マッチしたコマンドのヒストリを表示できるようにする
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end
# すべてのヒストリを表示する
function history-all { history -E 1 }

# ------------------------------
# Look And Feel Settings
# ------------------------------
### Ls Color ###
# 色の設定
export LSCOLORS=Exfxcxdxbxegedabagacad
# 補完時の色の設定
export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
# ZLS_COLORSとは？
export ZLS_COLORS=$LS_COLORS
# lsコマンド時、自動で色がつく(ls -Gのようなもの？)
export CLICOLOR=true
# 補完候補に色を付ける
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

## prompt ##
# Load version control information
autoload -Uz vcs_info
precmd() { vcs_info }
# Format the vcs_info_msg_0_ variable
zstyle ':vcs_info:git:*' formats '(%b)'
setopt PROMPT_SUBST
# PROMPT内で変数展開・コマンド置換・算術演算を実行する
setopt prompt_subst
## PROMPT内で「％」文字から始まる置換機能を有効にする
setopt prompt_percent
## コマンド実行後は右プロンプトを消す
setopt transient_rprompt 
# prompt
#  /sys/class/power_supply/BAT0/status : Charging ? Dischargingで色を変えたい
PROMPT='%K{red}%F{black}$(cat /sys/class/power_supply/BAT0/capacity)%% %k%K{green}%F{black}%/%f%k%K{cyan}%F{black}%D %T%f%k ${vcs_info_msg_0_}
[%j]%#'

## alias ##
alias ls='ls -h --color=auto'
alias fev='feh -. -g 1100x700'
alias tw='nekome tweet -e nvim'

 
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
zinit load zsh-users/zsh-syntax-highlighting

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zinit-zsh/z-a-rust \
    zinit-zsh/z-a-as-monitor \
    zinit-zsh/z-a-patch-dl \
    zinit-zsh/z-a-bin-gem-node

### End of Zinit's installer chunk

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[path]='fg=magenta'

# opam configuration
[[ ! -r /home/atled/.opam/opam-init/init.zsh ]] || source /home/atled/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

[ -f "/home/atled/.ghcup/env" ] && source "/home/atled/.ghcup/env" # ghcup-env
